config/routes.rb
 Rails.application.routes.draw do
    root :to => "articles#index"
    get 'new'   => 'articles#new'
    resources :articles
    resources :comments
    resources :users
    resources :article_imports
    resources :sessions
    get "sign_up" => "users#new", :as => "sign_up"
    resources :articles do
    	collection { post :import }
    end
end

app/models/article.rb
class Article < ActiveRecord::Base
  #name relation must plural
  has_many :comments, dependent: :destroy
  
	has_attached_file :image, 

	:path => ":rails_root/public/system/:attachment/:id/:basename_:style.:extension",
  :url => "/system/:attachment/:id/:basename_:style.:extension",

	:styles => { :medium => "300x300>", :thumb => "100x100>" }

	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  validates :title, presence: true,
  length: { minimum: 5 }

  validates :content, presence: true,
  length: { minimum: 10 }

  validates :status, presence: true

  def self.to_csv(option = {})
    CSV.generate(option) do |csv|
      csv << column_names
      all.each do |article|
        csv << article.attributes.values_at(*column_names)
      end
    end
  end

  

  def self.import(file)
    allowed_attributes = [ "title","content","status"]
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      product = find_by_id(row["id"]) || new
      product.attributes = row.to_hash.select { |k,v| allowed_attributes.include? k }
      product.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then Roo::Csv.new(file.path)
    when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :check_current_user, only: [:create, :edit, :update, :destroy]
  
  def index
  	@articles = Article.paginate(:page => params[:page], :per_page => 3, :order => "created_at DESC")
  end

  def show
  	@article = Article.find_by_id(params[:id])
    @comments = @article.comments.order("id desc")
    @comment = Comment.new
    respond_to do |format|
      format.html
      #format.csv { send_data @article.to_csv }
      format.xls
    end
  end

  def import
    Article.import(params[:file])
    redirect_to root_url, notice: "Articles imported"
  end

  def new
  	@article = Article.new
  end

  def create
  	@article = Article.new(params_article)
  	if @article.save
  		flash[:notice] = "Success Add Records"
  		redirect_to action: 'index'
  	else
  		flash[:error] = "data not valid"
  		render 'new'
  	end
  end

  def edit
  	@article = Article.find_by_id(params[:id])
  end
  
  def update
  	@article = Article.find_by_id(params[:id])

  	 if @article.update(params_article)

  	    flash[:notice] = "Success Update Records"

  	    redirect_to action: 'index'

  	 else

  	    flash[:error] = "data not valid"

  	    render 'edit'

  	 end
  end
  
  def destroy
  	@article = Article.find_by_id(params[:id])

    if @article.destroy

        flash[:notice] = "Success Delete a Records"

        redirect_to action: 'index'

    else

        flash[:error] = "fails delete a records"

        redirect_to action: 'index'

    end
  end

  private
  def params_article
  	params.require(:article).permit(:title, :content, :status, :image)
  end
end

app/views/articles/_comments.html.erb
<% @comments.each do |comment| %>

        <p>

        <b><%= comment.user.try(:username) %></b>

        <br />

        <%= comment.content %>

        </p>
        <hr>

    <% end %>

app/views/articles/_form.html.erb
<%= form_for @comment, url: comments_path, remote: true do |f| %>
    <%= f.hidden_field :article_id, value: @article.id %>
    <% if current_user %>
        <%= f.hidden_field :user_id, value: current_user.id %>
    <% end %>

    <div class="form-group">
        <%= f.label :content %>
        <%= f.text_area :content, class: "form-control" %>
    </div>
    <div class="row">
        <div class="col-md-6">
        </div>
        <div class="col-md-6">
            <div class="btn-group pull-right">
                <% if current_user %>
                <%= f.submit :submit, class: "btn btn-primary btn-sm", value: "Add Comment" %>
                <% else %>
                <%= link_to "Add Comment", new_session_path, class: "btn btn-primary btn-sm" %>
                <% end %>
            </div>
        </div>
    </div>

<% end %>

app/views/articles/edit.html.erb
<div class="row">
	<div class="col-md-6">
		<h1> Edit Article </h1>
		<hr>
		<%= form_for @article, :html => { :multipart => true} do |f| %>
			<%= f.label :image %><br>
			<%= image_tag @article.image.url(:thumb) %><br><br>
		<div class="form-group">	
			<%= f.file_field :image %>
		</div>

		<div class="form-group">
			<%= f.label :image %>
			<%= f.label :title %>
			<%= f.text_field :title, class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :content %>
			<%= f.text_area :content, class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :status %>
			<%= f.radio_button :status, "active" %>
			<%= label :article_status, 'active' %>
			<%= f.radio_button :status, "off" %>
			<%= label :article_status, 'off' %>
		</div>

		<div class="form-group">
			<%= f.submit :submit, value: "Edit", class: "btn btn-primary" %>
			<%= link_to "Back", articles_path, class: "btn btn-default" %>
		</div>
		<% end %>
	</div>
</div>

app/views/articles/index.html.erb
<div class="row">
	<div class="col-md-10 col-md-offset-1">	
		<h3>New Article</h3>
		<hr/>
	</div>
</div>
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<% @articles.each do |article| %>
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4><%= article.title %></h4>
			</div>
			<div class="panel-body">
				<p>
				<%= link_to (image_tag article.image.url(:medium)), article, class: "img-thumbnail", alt: "Responsive image" %>
				</p>
				<p><%= article.content %></p>
				<h5>Status : <%= article.status %></h5>
			</div>
			<div class="panel-footer">
				<div class="row">
					<div class="col-md-6">
					</div>
					<div class="col-md-6">
						<div class="pull-right">
							<% if current_user %>
							<%= link_to 'Edit', edit_article_path(article.id), class: "btn btn-sm btn-primary" %>
							<%= link_to 'Delete', article_path(article.id), class: "btn btn-sm btn-default", method: "DELETE", data: {confirm: 'Delete this data ? '} %>
							<% end %>
							<%= link_to 'View Comments', article, class: "btn btn-sm btn-default" %>
						</div>
					</div>
				</div>
			</div>
		</div>
		<hr/>
		<% end %>
		<%= will_paginate @articles, renderer: BootstrapPagination::Rails %>
	</div>
</div>

app/views/articles/new.html.erb
<div class="row">
	<div class="col-md-12">	
		<h1>New Article</h1>
		<hr/>
	</div>
</div>
<div class="row">
	<div class="col-md-6" style="border-right: 1px solid #ccc;">
		<div class="col-md-11">
			<%= form_for @article, :html => { :multipart => true} do |f| %>
			<div class="form-group">
				<%= f.label :image %>
				<%= f.file_field :image %>
			</div>

			<div class="form-group">
				<%= f.label :title %>
				<%= f.text_field :title, class: "form-control" %>
				<%= @article.errors[:title].first unless @article.errors[:title].blank? %>
			</div>

			<div class="form-group">
				<%= f.label :content %>
				<%= f.text_area :content, class: "form-control", cols:30, rows:10 %>
				<%= @article.errors[:content].first unless @article.errors[:content].blank? %>
			</div>
		
			<div class="form-group">
				<%= f.label :status %>
				<%= f.radio_button :status, "active" %>
				<%= label :article_status, 'active' %>
				<%= f.radio_button :status, "off", :checked => true %>
				<%= label :article_status, 'off' %>
			</div>

			<div class="form-group">
				<%= f.submit :submit, value: "Submit", class: "btn btn-primary" %>
				<%= link_to "Back", articles_path, class: "btn btn-default" %>
			</div>
			<% end %>
		</div>
	</div>
	<div class="col-md-6">
		<div class="col-md-11"> 
			<%= form_tag import_articles_path, multipart: true do %>
			<h4>Import new article with file <i>.csv</i> or <i>.xls</i> or <i>.xlsx</i></h4>
			<br>
			<div class="form-group">
			    <label class="col-sm-1 control-label">File</label>
			    <div class="col-sm-8">
			    	<%= file_field_tag :file %>
			    </div>
		  	</div>
		  	<br>
		  	<div class="form-group">
			    <div class="col-sm-offset-1 col-sm-8">
			    	<%= submit_tag "Import", class: "btn btn-default btn-sm" %>
			    </div>
		  	</div>
			<% end %>
		</div>
	</div>
</div>

app/views/articles/show.html.erb
<div id="pin_show" class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="panel panel-default">
			<div class="panel-heading pin_image">
				<%= @article.title %>
			</div>
			<div class="panel-body">
				<p><%= image_tag @article.image.url(:medium), class: "img-thumbnail" %></p>
				<p><%= @article.content %></p>
				<p>Status
					<%= @article.status %>
				</p>
			</div>
			<div class="panel-footer">
				<div class="row">
					<div class="col-md-6">
						<% if current_user %>
						Export : <%= link_to "Excel", article_path(format: "xls") %> | 
						<%= link_to "PDF", article_path(@article, :format => 'pdf') %>
						<% end %>
					</div>
					<div class="col-md-6">
						<div class="btn-group pull-right">
							<%= link_to 'back', root_path, class: "btn btn-default" %>
							<% if current_user %>
							<%= link_to 'edit', edit_article_path(@article.id), class: "btn btn-default" %>
							<%= link_to 'delete', article_path(@article.id), method: "DELETE", data: {confirm: 'Delete this data ? '}, class: "btn btn-default"  %>
							<% end %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="pin_show" class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="panel panel-default">
			<div class = "panel-heading">
				Add Comment :
			</div>
			<div class="panel-body">
				<div id="form-comment">
			        <%= render 'form' %>
			    </div>
			    <h5>Here the comments :</h5>
			    <div id="list-comments">
			        <%= render 'comments' %>
			    </div>
			</div>
		</div>
	</div>
</div>

app/views/articles/show.xls.erb
<b>Title :</b><br>
<%= @article.title %><br>
<b>Content :</b><br>
<%= @article.content %><br>
<b>Status:</b><br>
<%= @article.status %><br>

<b>Comments :</b>
<% @comments.each do |comment| %>

        <p>

        <b><%= comment.user.try(:username) %></b>

        <br />

        <%= comment.content %>

        </p>

    <% end %>